// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/card.dart';
import 'api/jwxt.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -258487831;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_njupt_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCardClearCardCache({required CardHandle card});

  Future<void> crateApiJwxtClearJwxtCache({required JwxtHandle jwxt});

  Future<void> crateApiJwxtEnsureSession({required JwxtHandle jwxt});

  Future<String> crateApiCardFetchCardBalance({
    required CardHandle card,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiCardFetchCardBalanceJson({
    required CardHandle card,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchDeferredExams({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchDeferredExamsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchExams({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchExamsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchGradeDetails({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchGradeDetailsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchGrades({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchGradesJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchMakeupExams({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchMakeupExamsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchProfile({
    required JwxtHandle jwxt,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchProfileFields({
    required JwxtHandle jwxt,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchSchedule({
    required JwxtHandle jwxt,
    required int year,
    required BridgeTerm term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchScheduleJson({
    required JwxtHandle jwxt,
    required int year,
    required BridgeTerm term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchSelected({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<String> crateApiJwxtFetchSelectedJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  });

  Future<SelectionContextHandle> crateApiJwxtFetchSelectionContext({
    required JwxtHandle jwxt,
  });

  Future<bool> crateApiJwxtHasCache({
    required JwxtHandle jwxt,
    required BridgeCacheKind kind,
    int? year,
    BridgeTerm? term,
  });

  Future<void> crateApiSimpleInitApp();

  Future<bool> crateApiJwxtInvalidateCache({
    required JwxtHandle jwxt,
    required BridgeCacheKind kind,
    int? year,
    BridgeTerm? term,
  });

  Future<void> crateApiJwxtInvalidateCacheKind({
    required JwxtHandle jwxt,
    required BridgeCacheKind kind,
  });

  Future<BigInt> crateApiJwxtJwxtCacheLen({required JwxtHandle jwxt});

  Future<JwxtHandle> crateApiJwxtLoginCampus({
    required String username,
    required String password,
  });

  Future<CardHandle> crateApiCardLoginCardCampus({
    required String username,
    required String password,
  });

  Future<CardHandle> crateApiCardLoginCardOffCampus({
    required String username,
    required String password,
  });

  Future<JwxtHandle> crateApiJwxtLoginOffCampus({
    required String username,
    required String password,
  });

  Future<String> crateApiJwxtSearchSelectableCourses({
    required JwxtHandle jwxt,
    required SelectionContextHandle ctx,
    required BridgeSelectableSearch query,
  });

  Future<String> crateApiJwxtSelectableClassDetails({
    required JwxtHandle jwxt,
    required SelectionContextHandle ctx,
    required BridgeClassDetailQuery query,
  });

  Future<String> crateApiJwxtSelectionChosen({
    required JwxtHandle jwxt,
    required SelectionContextHandle ctx,
    required int year,
    required BridgeTerm term,
  });

  Future<String> crateApiJwxtSelectionContextJson({
    required SelectionContextHandle ctx,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CardHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CardHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CardHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JwxtHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JwxtHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JwxtHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SelectionContextHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SelectionContextHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SelectionContextHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCardClearCardCache({required CardHandle card}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
            card,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCardClearCardCacheConstMeta,
        argValues: [card],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCardClearCardCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_card_cache", argNames: ["card"]);

  @override
  Future<void> crateApiJwxtClearJwxtCache({required JwxtHandle jwxt}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJwxtClearJwxtCacheConstMeta,
        argValues: [jwxt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtClearJwxtCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_jwxt_cache", argNames: ["jwxt"]);

  @override
  Future<void> crateApiJwxtEnsureSession({required JwxtHandle jwxt}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtEnsureSessionConstMeta,
        argValues: [jwxt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtEnsureSessionConstMeta =>
      const TaskConstMeta(debugName: "ensure_session", argNames: ["jwxt"]);

  @override
  Future<String> crateApiCardFetchCardBalance({
    required CardHandle card,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
            card,
            serializer,
          );
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCardFetchCardBalanceConstMeta,
        argValues: [card, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCardFetchCardBalanceConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_card_balance",
        argNames: ["card", "mode"],
      );

  @override
  Future<String> crateApiCardFetchCardBalanceJson({
    required CardHandle card,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
            card,
            serializer,
          );
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCardFetchCardBalanceJsonConstMeta,
        argValues: [card, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCardFetchCardBalanceJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_card_balance_json",
        argNames: ["card", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchDeferredExams({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchDeferredExamsConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchDeferredExamsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_deferred_exams",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchDeferredExamsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchDeferredExamsJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchDeferredExamsJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_deferred_exams_json",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchExams({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchExamsConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchExamsConstMeta => const TaskConstMeta(
    debugName: "fetch_exams",
    argNames: ["jwxt", "year", "term", "mode"],
  );

  @override
  Future<String> crateApiJwxtFetchExamsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchExamsJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchExamsJsonConstMeta => const TaskConstMeta(
    debugName: "fetch_exams_json",
    argNames: ["jwxt", "year", "term", "mode"],
  );

  @override
  Future<String> crateApiJwxtFetchGradeDetails({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchGradeDetailsConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchGradeDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_grade_details",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchGradeDetailsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchGradeDetailsJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchGradeDetailsJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_grade_details_json",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchGrades({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchGradesConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchGradesConstMeta => const TaskConstMeta(
    debugName: "fetch_grades",
    argNames: ["jwxt", "year", "term", "mode"],
  );

  @override
  Future<String> crateApiJwxtFetchGradesJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchGradesJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchGradesJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_grades_json",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchMakeupExams({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchMakeupExamsConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchMakeupExamsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_makeup_exams",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchMakeupExamsJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchMakeupExamsJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchMakeupExamsJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_makeup_exams_json",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchProfile({
    required JwxtHandle jwxt,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchProfileConstMeta,
        argValues: [jwxt, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchProfileConstMeta => const TaskConstMeta(
    debugName: "fetch_profile",
    argNames: ["jwxt", "mode"],
  );

  @override
  Future<String> crateApiJwxtFetchProfileFields({
    required JwxtHandle jwxt,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchProfileFieldsConstMeta,
        argValues: [jwxt, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchProfileFieldsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_profile_fields",
        argNames: ["jwxt", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchSchedule({
    required JwxtHandle jwxt,
    required int year,
    required BridgeTerm term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_u_32(year, serializer);
          sse_encode_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchScheduleConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchScheduleConstMeta => const TaskConstMeta(
    debugName: "fetch_schedule",
    argNames: ["jwxt", "year", "term", "mode"],
  );

  @override
  Future<String> crateApiJwxtFetchScheduleJson({
    required JwxtHandle jwxt,
    required int year,
    required BridgeTerm term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_u_32(year, serializer);
          sse_encode_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchScheduleJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchScheduleJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_schedule_json",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<String> crateApiJwxtFetchSelected({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchSelectedConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchSelectedConstMeta => const TaskConstMeta(
    debugName: "fetch_selected",
    argNames: ["jwxt", "year", "term", "mode"],
  );

  @override
  Future<String> crateApiJwxtFetchSelectedJson({
    required JwxtHandle jwxt,
    int? year,
    BridgeTerm? term,
    required BridgeFetchMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          sse_encode_bridge_fetch_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchSelectedJsonConstMeta,
        argValues: [jwxt, year, term, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchSelectedJsonConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_selected_json",
        argNames: ["jwxt", "year", "term", "mode"],
      );

  @override
  Future<SelectionContextHandle> crateApiJwxtFetchSelectionContext({
    required JwxtHandle jwxt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtFetchSelectionContextConstMeta,
        argValues: [jwxt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtFetchSelectionContextConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_selection_context",
        argNames: ["jwxt"],
      );

  @override
  Future<bool> crateApiJwxtHasCache({
    required JwxtHandle jwxt,
    required BridgeCacheKind kind,
    int? year,
    BridgeTerm? term,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_bridge_cache_kind(kind, serializer);
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJwxtHasCacheConstMeta,
        argValues: [jwxt, kind, year, term],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtHasCacheConstMeta => const TaskConstMeta(
    debugName: "has_cache",
    argNames: ["jwxt", "kind", "year", "term"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiJwxtInvalidateCache({
    required JwxtHandle jwxt,
    required BridgeCacheKind kind,
    int? year,
    BridgeTerm? term,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_bridge_cache_kind(kind, serializer);
          sse_encode_opt_box_autoadd_u_32(year, serializer);
          sse_encode_opt_box_autoadd_bridge_term(term, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJwxtInvalidateCacheConstMeta,
        argValues: [jwxt, kind, year, term],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtInvalidateCacheConstMeta =>
      const TaskConstMeta(
        debugName: "invalidate_cache",
        argNames: ["jwxt", "kind", "year", "term"],
      );

  @override
  Future<void> crateApiJwxtInvalidateCacheKind({
    required JwxtHandle jwxt,
    required BridgeCacheKind kind,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_bridge_cache_kind(kind, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJwxtInvalidateCacheKindConstMeta,
        argValues: [jwxt, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtInvalidateCacheKindConstMeta =>
      const TaskConstMeta(
        debugName: "invalidate_cache_kind",
        argNames: ["jwxt", "kind"],
      );

  @override
  Future<BigInt> crateApiJwxtJwxtCacheLen({required JwxtHandle jwxt}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJwxtJwxtCacheLenConstMeta,
        argValues: [jwxt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtJwxtCacheLenConstMeta =>
      const TaskConstMeta(debugName: "jwxt_cache_len", argNames: ["jwxt"]);

  @override
  Future<JwxtHandle> crateApiJwxtLoginCampus({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtLoginCampusConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtLoginCampusConstMeta => const TaskConstMeta(
    debugName: "login_campus",
    argNames: ["username", "password"],
  );

  @override
  Future<CardHandle> crateApiCardLoginCardCampus({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCardLoginCardCampusConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCardLoginCardCampusConstMeta =>
      const TaskConstMeta(
        debugName: "login_card_campus",
        argNames: ["username", "password"],
      );

  @override
  Future<CardHandle> crateApiCardLoginCardOffCampus({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCardLoginCardOffCampusConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCardLoginCardOffCampusConstMeta =>
      const TaskConstMeta(
        debugName: "login_card_off_campus",
        argNames: ["username", "password"],
      );

  @override
  Future<JwxtHandle> crateApiJwxtLoginOffCampus({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtLoginOffCampusConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtLoginOffCampusConstMeta => const TaskConstMeta(
    debugName: "login_off_campus",
    argNames: ["username", "password"],
  );

  @override
  Future<String> crateApiJwxtSearchSelectableCourses({
    required JwxtHandle jwxt,
    required SelectionContextHandle ctx,
    required BridgeSelectableSearch query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
            ctx,
            serializer,
          );
          sse_encode_box_autoadd_bridge_selectable_search(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtSearchSelectableCoursesConstMeta,
        argValues: [jwxt, ctx, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtSearchSelectableCoursesConstMeta =>
      const TaskConstMeta(
        debugName: "search_selectable_courses",
        argNames: ["jwxt", "ctx", "query"],
      );

  @override
  Future<String> crateApiJwxtSelectableClassDetails({
    required JwxtHandle jwxt,
    required SelectionContextHandle ctx,
    required BridgeClassDetailQuery query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
            ctx,
            serializer,
          );
          sse_encode_box_autoadd_bridge_class_detail_query(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtSelectableClassDetailsConstMeta,
        argValues: [jwxt, ctx, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtSelectableClassDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "selectable_class_details",
        argNames: ["jwxt", "ctx", "query"],
      );

  @override
  Future<String> crateApiJwxtSelectionChosen({
    required JwxtHandle jwxt,
    required SelectionContextHandle ctx,
    required int year,
    required BridgeTerm term,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
            jwxt,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
            ctx,
            serializer,
          );
          sse_encode_u_32(year, serializer);
          sse_encode_bridge_term(term, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtSelectionChosenConstMeta,
        argValues: [jwxt, ctx, year, term],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtSelectionChosenConstMeta =>
      const TaskConstMeta(
        debugName: "selection_chosen",
        argNames: ["jwxt", "ctx", "year", "term"],
      );

  @override
  Future<String> crateApiJwxtSelectionContextJson({
    required SelectionContextHandle ctx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
            ctx,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJwxtSelectionContextJsonConstMeta,
        argValues: [ctx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJwxtSelectionContextJsonConstMeta =>
      const TaskConstMeta(
        debugName: "selection_context_json",
        argNames: ["ctx"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CardHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CardHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JwxtHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JwxtHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SelectionContextHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SelectionContextHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle;

  @protected
  CardHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JwxtHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JwxtHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SelectionContextHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SelectionContextHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  CardHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JwxtHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JwxtHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SelectionContextHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SelectionContextHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  CardHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JwxtHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JwxtHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SelectionContextHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SelectionContextHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeClassDetailQuery dco_decode_box_autoadd_bridge_class_detail_query(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_class_detail_query(raw);
  }

  @protected
  BridgeSelectableSearch dco_decode_box_autoadd_bridge_selectable_search(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_selectable_search(raw);
  }

  @protected
  BridgeTerm dco_decode_box_autoadd_bridge_term(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_term(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BridgeCacheKind dco_decode_bridge_cache_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeCacheKind.values[raw as int];
  }

  @protected
  BridgeClassDetailQuery dco_decode_bridge_class_detail_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BridgeClassDetailQuery(
      year: dco_decode_u_32(arr[0]),
      term: dco_decode_bridge_term(arr[1]),
      kklxdm: dco_decode_String(arr[2]),
      kchId: dco_decode_String(arr[3]),
      xkkzId: dco_decode_String(arr[4]),
    );
  }

  @protected
  BridgeFetchMode dco_decode_bridge_fetch_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeFetchMode.values[raw as int];
  }

  @protected
  BridgeSelectableSearch dco_decode_bridge_selectable_search(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeSelectableSearch(
      year: dco_decode_u_32(arr[0]),
      term: dco_decode_bridge_term(arr[1]),
      kklxdm: dco_decode_String(arr[2]),
      filter: dco_decode_opt_String(arr[3]),
      pageStart: dco_decode_u_32(arr[4]),
      pageEnd: dco_decode_u_32(arr[5]),
      onlyAvailable: dco_decode_bool(arr[6]),
    );
  }

  @protected
  BridgeTerm dco_decode_bridge_term(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeTerm.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BridgeTerm? dco_decode_opt_box_autoadd_bridge_term(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_term(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CardHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CardHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JwxtHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JwxtHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SelectionContextHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SelectionContextHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CardHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CardHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JwxtHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JwxtHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SelectionContextHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SelectionContextHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CardHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CardHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JwxtHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JwxtHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SelectionContextHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SelectionContextHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeClassDetailQuery sse_decode_box_autoadd_bridge_class_detail_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_class_detail_query(deserializer));
  }

  @protected
  BridgeSelectableSearch sse_decode_box_autoadd_bridge_selectable_search(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_selectable_search(deserializer));
  }

  @protected
  BridgeTerm sse_decode_box_autoadd_bridge_term(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_term(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BridgeCacheKind sse_decode_bridge_cache_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeCacheKind.values[inner];
  }

  @protected
  BridgeClassDetailQuery sse_decode_bridge_class_detail_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_u_32(deserializer);
    var var_term = sse_decode_bridge_term(deserializer);
    var var_kklxdm = sse_decode_String(deserializer);
    var var_kchId = sse_decode_String(deserializer);
    var var_xkkzId = sse_decode_String(deserializer);
    return BridgeClassDetailQuery(
      year: var_year,
      term: var_term,
      kklxdm: var_kklxdm,
      kchId: var_kchId,
      xkkzId: var_xkkzId,
    );
  }

  @protected
  BridgeFetchMode sse_decode_bridge_fetch_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeFetchMode.values[inner];
  }

  @protected
  BridgeSelectableSearch sse_decode_bridge_selectable_search(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_u_32(deserializer);
    var var_term = sse_decode_bridge_term(deserializer);
    var var_kklxdm = sse_decode_String(deserializer);
    var var_filter = sse_decode_opt_String(deserializer);
    var var_pageStart = sse_decode_u_32(deserializer);
    var var_pageEnd = sse_decode_u_32(deserializer);
    var var_onlyAvailable = sse_decode_bool(deserializer);
    return BridgeSelectableSearch(
      year: var_year,
      term: var_term,
      kklxdm: var_kklxdm,
      filter: var_filter,
      pageStart: var_pageStart,
      pageEnd: var_pageEnd,
      onlyAvailable: var_onlyAvailable,
    );
  }

  @protected
  BridgeTerm sse_decode_bridge_term(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeTerm.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeTerm? sse_decode_opt_box_autoadd_bridge_term(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_term(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    CardHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CardHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    JwxtHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JwxtHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    SelectionContextHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SelectionContextHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    CardHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CardHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    JwxtHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JwxtHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    SelectionContextHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SelectionContextHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCardHandle(
    CardHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CardHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJwxtHandle(
    JwxtHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JwxtHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSelectionContextHandle(
    SelectionContextHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SelectionContextHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_class_detail_query(
    BridgeClassDetailQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_class_detail_query(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_selectable_search(
    BridgeSelectableSearch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_selectable_search(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_term(
    BridgeTerm self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_term(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_bridge_cache_kind(
    BridgeCacheKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_class_detail_query(
    BridgeClassDetailQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.year, serializer);
    sse_encode_bridge_term(self.term, serializer);
    sse_encode_String(self.kklxdm, serializer);
    sse_encode_String(self.kchId, serializer);
    sse_encode_String(self.xkkzId, serializer);
  }

  @protected
  void sse_encode_bridge_fetch_mode(
    BridgeFetchMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_selectable_search(
    BridgeSelectableSearch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.year, serializer);
    sse_encode_bridge_term(self.term, serializer);
    sse_encode_String(self.kklxdm, serializer);
    sse_encode_opt_String(self.filter, serializer);
    sse_encode_u_32(self.pageStart, serializer);
    sse_encode_u_32(self.pageEnd, serializer);
    sse_encode_bool(self.onlyAvailable, serializer);
  }

  @protected
  void sse_encode_bridge_term(BridgeTerm self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_term(
    BridgeTerm? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_term(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CardHandleImpl extends RustOpaque implements CardHandle {
  // Not to be used by end users
  CardHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CardHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CardHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CardHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CardHandlePtr,
  );
}

@sealed
class JwxtHandleImpl extends RustOpaque implements JwxtHandle {
  // Not to be used by end users
  JwxtHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  JwxtHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_JwxtHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_JwxtHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_JwxtHandlePtr,
  );
}

@sealed
class SelectionContextHandleImpl extends RustOpaque
    implements SelectionContextHandle {
  // Not to be used by end users
  SelectionContextHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SelectionContextHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_SelectionContextHandle,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SelectionContextHandle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SelectionContextHandlePtr,
  );
}
