// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'jwxt.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cached_json`, `mode_of`

Future<CardHandle> loginCardCampus({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiCardLoginCardCampus(
  username: username,
  password: password,
);

Future<CardHandle> loginCardOffCampus({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiCardLoginCardOffCampus(
  username: username,
  password: password,
);

Future<String> fetchCardBalance({
  required CardHandle card,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiCardFetchCardBalance(card: card, mode: mode);

Future<String> fetchCardBalanceJson({
  required CardHandle card,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiCardFetchCardBalanceJson(
  card: card,
  mode: mode,
);

Future<void> clearCardCache({required CardHandle card}) =>
    RustLib.instance.api.crateApiCardClearCardCache(card: card);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CardHandle>>
abstract class CardHandle implements RustOpaqueInterface {}
