// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cached_json`, `cached_value`, `kind_of`, `mode_of`, `term_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

Future<JwxtHandle> loginCampus({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiJwxtLoginCampus(
  username: username,
  password: password,
);

Future<JwxtHandle> loginOffCampus({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiJwxtLoginOffCampus(
  username: username,
  password: password,
);

Future<void> ensureSession({required JwxtHandle jwxt}) =>
    RustLib.instance.api.crateApiJwxtEnsureSession(jwxt: jwxt);

Future<String> fetchSchedule({
  required JwxtHandle jwxt,
  required int year,
  required BridgeTerm term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchSchedule(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchScheduleJson({
  required JwxtHandle jwxt,
  required int year,
  required BridgeTerm term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchScheduleJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchGrades({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchGrades(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchGradesJson({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchGradesJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchGradeDetails({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchGradeDetails(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchGradeDetailsJson({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchGradeDetailsJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchExams({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchExams(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchExamsJson({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchExamsJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchMakeupExams({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchMakeupExams(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchMakeupExamsJson({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchMakeupExamsJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchDeferredExams({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchDeferredExams(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchDeferredExamsJson({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchDeferredExamsJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchSelected({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchSelected(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchSelectedJson({
  required JwxtHandle jwxt,
  int? year,
  BridgeTerm? term,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchSelectedJson(
  jwxt: jwxt,
  year: year,
  term: term,
  mode: mode,
);

Future<String> fetchProfile({
  required JwxtHandle jwxt,
  required BridgeFetchMode mode,
}) => RustLib.instance.api.crateApiJwxtFetchProfile(jwxt: jwxt, mode: mode);

Future<String> fetchProfileFields({
  required JwxtHandle jwxt,
  required BridgeFetchMode mode,
}) =>
    RustLib.instance.api.crateApiJwxtFetchProfileFields(jwxt: jwxt, mode: mode);

Future<SelectionContextHandle> fetchSelectionContext({
  required JwxtHandle jwxt,
}) => RustLib.instance.api.crateApiJwxtFetchSelectionContext(jwxt: jwxt);

Future<String> selectionContextJson({required SelectionContextHandle ctx}) =>
    RustLib.instance.api.crateApiJwxtSelectionContextJson(ctx: ctx);

Future<String> searchSelectableCourses({
  required JwxtHandle jwxt,
  required SelectionContextHandle ctx,
  required BridgeSelectableSearch query,
}) => RustLib.instance.api.crateApiJwxtSearchSelectableCourses(
  jwxt: jwxt,
  ctx: ctx,
  query: query,
);

Future<String> selectableClassDetails({
  required JwxtHandle jwxt,
  required SelectionContextHandle ctx,
  required BridgeClassDetailQuery query,
}) => RustLib.instance.api.crateApiJwxtSelectableClassDetails(
  jwxt: jwxt,
  ctx: ctx,
  query: query,
);

Future<String> selectionChosen({
  required JwxtHandle jwxt,
  required SelectionContextHandle ctx,
  required int year,
  required BridgeTerm term,
}) => RustLib.instance.api.crateApiJwxtSelectionChosen(
  jwxt: jwxt,
  ctx: ctx,
  year: year,
  term: term,
);

Future<bool> hasCache({
  required JwxtHandle jwxt,
  required BridgeCacheKind kind,
  int? year,
  BridgeTerm? term,
}) => RustLib.instance.api.crateApiJwxtHasCache(
  jwxt: jwxt,
  kind: kind,
  year: year,
  term: term,
);

Future<bool> invalidateCache({
  required JwxtHandle jwxt,
  required BridgeCacheKind kind,
  int? year,
  BridgeTerm? term,
}) => RustLib.instance.api.crateApiJwxtInvalidateCache(
  jwxt: jwxt,
  kind: kind,
  year: year,
  term: term,
);

Future<void> invalidateCacheKind({
  required JwxtHandle jwxt,
  required BridgeCacheKind kind,
}) => RustLib.instance.api.crateApiJwxtInvalidateCacheKind(
  jwxt: jwxt,
  kind: kind,
);

Future<void> clearJwxtCache({required JwxtHandle jwxt}) =>
    RustLib.instance.api.crateApiJwxtClearJwxtCache(jwxt: jwxt);

Future<BigInt> jwxtCacheLen({required JwxtHandle jwxt}) =>
    RustLib.instance.api.crateApiJwxtJwxtCacheLen(jwxt: jwxt);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JwxtHandle>>
abstract class JwxtHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SelectionContextHandle>>
abstract class SelectionContextHandle implements RustOpaqueInterface {}

enum BridgeCacheKind {
  grades,
  gradeDetails,
  schedule,
  exams,
  makeupExams,
  deferredExams,
  selected,
  profile,
}

class BridgeClassDetailQuery {
  final int year;
  final BridgeTerm term;
  final String kklxdm;
  final String kchId;
  final String xkkzId;

  const BridgeClassDetailQuery({
    required this.year,
    required this.term,
    required this.kklxdm,
    required this.kchId,
    required this.xkkzId,
  });

  @override
  int get hashCode =>
      year.hashCode ^
      term.hashCode ^
      kklxdm.hashCode ^
      kchId.hashCode ^
      xkkzId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClassDetailQuery &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          term == other.term &&
          kklxdm == other.kklxdm &&
          kchId == other.kchId &&
          xkkzId == other.xkkzId;
}

enum BridgeFetchMode { cacheFirst, networkOnly }

class BridgeSelectableSearch {
  final int year;
  final BridgeTerm term;
  final String kklxdm;
  final String? filter;
  final int pageStart;
  final int pageEnd;
  final bool onlyAvailable;

  const BridgeSelectableSearch({
    required this.year,
    required this.term,
    required this.kklxdm,
    this.filter,
    required this.pageStart,
    required this.pageEnd,
    required this.onlyAvailable,
  });

  @override
  int get hashCode =>
      year.hashCode ^
      term.hashCode ^
      kklxdm.hashCode ^
      filter.hashCode ^
      pageStart.hashCode ^
      pageEnd.hashCode ^
      onlyAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSelectableSearch &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          term == other.term &&
          kklxdm == other.kklxdm &&
          filter == other.filter &&
          pageStart == other.pageStart &&
          pageEnd == other.pageEnd &&
          onlyAvailable == other.onlyAvailable;
}

enum BridgeTerm { first, second }
